name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: ECR
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URL }}

      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . -t whisper -f docker/Dockerfile.gpu

      - name: Tag docker image
        run: docker tag whisper:dev ${{ secrets.ECR_REPOSITORY_URL }}/whisper:dev

      - name: Push docker image
        run: docker push ${{ secrets.ECR_REPOSITORY_URL }}/whisper:dev
