name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ECR_REPOSITORY_URL: ${{ secrets.ECR_REPOSITORY_URL }}

    steps:
      # - name: Delete huge unnecessary tools folder
      #   run: rm -rf /opt/hostedtoolcache
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${{ env.ECR_REPOSITORY_URL }}

      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . -t whisper -f docker/Dockerfile.gpu

      - name: Tag docker image
        run: docker tag whisper:latest ${{ env.ECR_REPOSITORY_URL }}/whisper:latest

      - name: Push docker image
        run: docker push ${{ env.ECR_REPOSITORY_URL }}/whisper:latest
